#!/bin/sh
# Assemble Pokémon Kanto Squad from the parts in this folder (order matters: later parts use earlier globals).
#   pokemon/index.html       full document
#   pokemon/dist/index.html  body-only copy for a claude.ai artifact (gitignored)
# Sprites in pokemon/sprites/ (tools/fetch_sprites.sh) are embedded as base64 so the game is a single file.
set -e
SRC=$(cd "$(dirname "$0")" && pwd)
OUT=$(dirname "$SRC")
mkdir -p "$OUT/dist"
# front/back are animation sheets with their playback lists in anim.json, icons their first frames
# (tools/pack_sprites.py); trainers are stills.
node -e '
const fs = require("fs"), p = require("path"), d = process.argv[1], out = { f: {}, b: {}, i: {}, t: {}, a: JSON.parse(fs.readFileSync(p.join(d, "anim.json"), "utf8")) };
for (const [k, dir] of [["f", "front"], ["b", "back"], ["i", "icons"], ["t", "trainers"]])
  for (const f of fs.readdirSync(p.join(d, dir)).filter(f => f.endsWith(".png")).sort()) out[k][f.slice(0, -4)] = fs.readFileSync(p.join(d, dir, f)).toString("base64");
for (const k of ["f", "b"]) for (const id in out[k]) if (!out.a[k][id]) throw new Error("no playback list for " + k + ":" + id);
fs.writeFileSync(process.argv[2], "\n// Pokémon Showdown sprites (base64 PNG) and animation playback lists, generated by build.sh\nconst SPR_DATA = " + JSON.stringify(out) + ";\n");
' "$OUT/sprites" "$OUT/dist/sprites.js"
BODY="$SRC/a2_core.js $SRC/a3a_dex.js $SRC/a3b_kits.js $OUT/dist/sprites.js $SRC/a4_story.js $SRC/a5_sprites.js $SRC/a6_state.js $SRC/a7_engine.js $SRC/a8a_render.js $SRC/a8c_sfx.js $SRC/a8b_battle.js $SRC/a9a_screens.js $SRC/a9b_screens.js $SRC/a9c_meta.js $SRC/a9d_gameboy.js $SRC/a10_boot.js"
{
  printf '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
  printf '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">\n'
  printf '<meta name="theme-color" content="#e3350d">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="mobile-web-app-capable" content="yes">\n'
  cat "$SRC/a1_head.html"
  printf '</head>\n<body>\n'
  cat $BODY
  printf '</body>\n</html>\n'
} > "$OUT/index.html"
cat "$SRC/a1_head.html" $BODY > "$OUT/dist/index.html"
awk '/<script>/{f=1;next}/<\/script>/{f=0}f' $BODY > "$OUT/dist/check.js"
node --check "$OUT/dist/check.js" && echo "syntax ok"
wc -c "$OUT/index.html"
